### ISSUE TITLE
[question]初始化失败

### ISSUE THREAD

**Issue by 1939323749** [bestcondition/poe-cmd#1]
`poe-cmd init MYCOOKIE MYCHANNEL`

/usr/local/share/npm-global/lib/node_modules/poe-cmd/dist/app_init.js:96
        return obj.props.pageProps.payload.chatOfBotDisplayName.chatId;
                                                                ^

TypeError: Cannot read properties of undefined (reading 'chatId')
    at HomePageParser.get_chat_id (/usr/local/share/npm-global/lib/node_modules/poe-cmd/dist/app_init.js:96:65)
    at /usr/local/share/npm-global/lib/node_modules/poe-cmd/dist/app_init.js:129:38
    at step (/usr/local/share/npm-global/lib/node_modules/poe-cmd/dist/app_init.js:56:23)
    at Object.next (/usr/local/share/npm-global/lib/node_modules/poe-cmd/dist/app_init.js:37:53)
    at fulfilled (/usr/local/share/npm-global/lib/node_modules/poe-cmd/dist/app_init.js:28:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.0.0

环境：
Linux 10a11365d981 6.3.4-orbstack-00151-g5c9dc5b64d8c #1 SMP Tue May 30 02:34:53 UTC 2023 aarch64 GNU/Linux
ts-node v10.9.1
npm 9.6.4

**Comment by bestcondition** [comment]
代理工具最好开一下`tun/tap`模式

`cookie`和`channel`是不是复制错了, 格式大概是下面这样

cookie: `p-b=xxxxxxxxx-xxxxxxxxxxxx%3D%3D`

channel: `poe-chan99-9999-echaxqjknkiphkvkqorw`

初始化语句大概是这样

```shell
poe-cmd init p-b=xxxxxxxxx-xxxxxxxxxxxx%3D%3D poe-chan99-9999-echaxqjknkiphkvkqorw
```

**Comment by 1939323749** [comment]
已经解决：cookie没有`p-b=`前缀，另外，v2ex上的初始化命令中cookie和channel写反了:
<img width="600" alt="image" src="https://github.com/bestcondition/poe-cmd/assets/28222273/c88ac2f8-7d3b-4a90-a560-9da7fd7a563c">
